# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b94f332c628d20c8d7edde3ecf03a098e264c281ab3f84ea8cc635e275e8c42c74137fa810224525a4b9efb87f9d3ed4f3959534e0caeac1f9288647c0b83ae6

test:
  secret_key_base: 0e742fd36a56481bb37b86d5487d20a00653c15482a533fe3b26221fdc842031f8c6403457e50bbb3300798d43b3f92a7a2c4d2f7c1a234011b885ab6ade252c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
